# Usa una imagen base de Python
FROM python:3.12

# Instalar dependencias del sistema necesarias
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    libgtk-3-0 \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libasound2-dev \
    portaudio19-dev \
    && rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY . /app

# Instala dependencias
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto donde correrá FastAPI
EXPOSE 8080

# Variables de entorno necesarias para OpenCV
ENV DISPLAY=:99

# Comando para ejecutar la aplicación
CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8080"]
